# Generated by Django 2.1.2 on 2018-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dingyi', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFish',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dingyi', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_fish',
                'managed': False,
            },
        ),
    ]
